# Generated by Django 3.1.7 on 2021-03-25 17:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(auto_created=True,
                                        default=uuid.uuid4,
                                        editable=False,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='Идентификатор')),
                ('name', models.CharField(default='',
                                          help_text='Наименование',
                                          max_length=50,
                                          verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.UUIDField(auto_created=True,
                                        default=uuid.uuid4,
                                        editable=False,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='Идентификатор')),
                ('name', models.CharField(default='',
                                          help_text='Наименование',
                                          max_length=50,
                                          verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавец',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(auto_created=True,
                                        default=uuid.uuid4,
                                        editable=False,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='Идентификатор')),
                ('name', models.CharField(default='',
                                          help_text='Наименование',
                                          max_length=30,
                                          verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.UUIDField(auto_created=True,
                                        default=uuid.uuid4,
                                        editable=False,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='Идентификатор')),
                ('name', models.CharField(default='',
                                          help_text='Наименование',
                                          max_length=200,
                                          verbose_name='Наименование')),
                ('description', models.CharField(default='',
                                                 help_text='Подробное описание',
                                                 max_length=500,
                                                 verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2,
                                              help_text='Цена товара',
                                              max_digits=10,
                                              verbose_name='Цена')),
                ('category', models.ForeignKey(help_text='Категория товара',
                                               on_delete=django.db.models.deletion.PROTECT,
                                               related_name='goods',
                                               to='main.category',
                                               verbose_name='Категория')),
                ('seller', models.ForeignKey(help_text='Продавец товара',
                                             on_delete=django.db.models.deletion.PROTECT,
                                             related_name='goods',
                                             to='main.seller',
                                             verbose_name='Продавец')),
                ('tags', models.ManyToManyField(help_text='Тэги',
                                                related_name='goods',
                                                to='main.Tag',
                                                verbose_name='Тэги')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
