# Generated by Django 3.1.7 on 2021-03-25 21:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(auto_created=True,
                                        default=uuid.uuid4,
                                        editable=False,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='Идентификатор')),
                ('iso3', models.CharField(default='',
                                          help_text='ISO3',
                                          max_length=3,
                                          verbose_name='ISO3')),
                ('name', models.CharField(default='',
                                          help_text='Наименование',
                                          max_length=50,
                                          verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.AddField(
            model_name='seller',
            name='country',
            field=models.ForeignKey(help_text='Страна',
                                    null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    related_name='sellers',
                                    to='main.country',
                                    verbose_name='Страна'),
        ),
    ]
