# Generated by Django 3.1.7 on 2021-05-06 15:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20210326_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='counter',
            field=models.PositiveIntegerField(default=0,
                                              editable=False,
                                              help_text='Счетчик',
                                              verbose_name='Счетчик'),
        ),
        migrations.AddField(
            model_name='good',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True,
                                                   null=True,
                                                   upload_to='main/static/images/goods',
                                                   verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('description', models.CharField(default='',
                                                 help_text='Описание',
                                                 max_length=100,
                                                 verbose_name='Описание')),
                ('birth_date', models.DateField(default=datetime.date.today,
                                                help_text='Дата рождения',
                                                verbose_name='Дата рождения')),
                ('image', sorl.thumbnail.fields.ImageField(null=True,
                                                           upload_to='main/static/images/users',
                                                           verbose_name='Изображение')),
                ('is_subscriber', models.BooleanField(default=False,
                                                      help_text='Cообщать о новинках',
                                                      verbose_name='Cообщать о новинках')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                              to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(auto_created=True,
                                        default=uuid.uuid4,
                                        editable=False,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='Идентификатор')),
                ('good', models.ForeignKey(help_text='Товар',
                                           null=True,
                                           on_delete=django.db.models.deletion.CASCADE,
                                           related_name='subscriptions',
                                           to='main.good',
                                           verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
