# Generated by Django 3.1.7 on 2021-04-07 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def set_users_to_profiles(apps, schema_editor):
    Profiles = apps.get_model('main', 'UserProfile')
    # Копируем ид профиля в связь так как ранее в него записывался ид пользователя
    for profile in Profiles.objects.all():
        profile.user_id = profile.id
        profile.save()

def reverse_users_to_profiles(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20210407_2044'),
    ]

    operations = [
        migrations.RunPython(set_users_to_profiles, reverse_users_to_profiles),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
