# Generated by Django 3.1.7 on 2021-04-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210407_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.CharField(default='', help_text='Описание', max_length=100, verbose_name='Описание'),
        ),
    ]
