# Generated by Django 3.1.7 on 2021-04-11 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_userprofile_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
    ]
