# Generated by Django 3.1.7 on 2021-04-11 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_userprofile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(default=datetime.date.today, help_text='Дата рождения', verbose_name='Дата рождения'),
        ),
    ]
