# Generated by Django 3.1.7 on 2021-04-11 18:32

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='whatever', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='whatever', verbose_name='Изображение'),
        ),
    ]
