# Generated by Django 3.1.7 on 2021-04-11 20:34

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210411_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
