# Generated by Django 3.1.7 on 2021-04-12 17:16

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210412_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='main/static/images/goods', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='main/static/images/users', verbose_name='Изображение'),
        ),
    ]
