# Generated by Django 3.1.7 on 2021-04-12 19:05

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='main/static/images/users', verbose_name='Изображение'),
        ),
    ]
