# Generated by Django 3.1.7 on 2021-04-17 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210417_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='good',
        ),
    ]
