# Generated by Django 3.1.7 on 2021-04-18 10:44

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210418_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='main/static/images/goods', verbose_name='Изображение'),
        ),
    ]
