# Generated by Django 3.1.7 on 2021-04-18 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210418_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='good',
            field=models.ForeignKey(help_text='Товар', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='main.good', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_subscriber',
            field=models.BooleanField(default=False, help_text='Получать сообщения о новинках', verbose_name='Получать сообщения о новинках'),
        ),
    ]
