# Generated by Django 3.1.7 on 2021-04-18 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210418_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='good',
            field=models.ForeignKey(help_text='Товар', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='main.good', verbose_name='Товар'),
        ),
    ]
