# Generated by Django 3.1.7 on 2021-04-18 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210418_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='user',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='good',
            field=models.ForeignKey(help_text='Товар', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='main.good', verbose_name='Товар'),
        ),
    ]
