# Generated by Django 3.1.7 on 2021-05-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20210418_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='counter',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Счетчик', verbose_name='Счетчик'),
        ),
    ]
